name: Metaworld-v2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==2.0.0
    - aiohappyeyeballs==2.4.0
    - aiohttp==3.10.5
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.4.0
    - appdirs==1.4.4
    - astor==0.8.1
    - async-timeout==4.0.3
    - attrs==24.2.0
    - av==12.3.0
    - blessed==1.20.0
    - cachetools==5.5.0
    - certifi==2023.7.22
    - cffi==1.17.1
    - charset-normalizer==3.3.2
    - click==8.0.4
    - cloudpickle==3.0.0
    - cmake==3.30.2
    - contourpy==1.1.1
    - cycler==0.12.1
    - cython==0.29.21
    - distlib==0.3.8
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - eval-type-backport==0.2.2
    - exceptiongroup==1.2.2
    - farama-notifications==0.0.4
    - fasteners==0.19
    - fastrand==1.8.0
    - filelock==3.15.4
    - fonttools==4.53.1
    - frozenlist==1.4.1
    - fsspec==2024.6.1
    - gitdb==4.0.11
    - gitpython==3.1.40
    - glfw==2.6.2
    - google-auth==2.34.0
    - google-auth-oauthlib==0.4.6
    - gpustat==1.1.1
    - grpcio==1.43.0
    - gym==0.23.1
    - gym-notices==0.0.8
    - gymnasium==0.29.1
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.2
    - hydra-core==1.3.2
    - idna==3.4
    - imageio==2.32.0
    - imageio-ffmpeg==0.5.1
    - importlib-metadata==6.8.0
    - importlib-resources==6.4.4
    - jinja2==3.1.4
    - jiter==0.5.0
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.7
    - levenshtein==0.25.1
    - libcst==1.1.0
    - lit==18.1.8
    - markdown==3.7
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - metaworld==2.0.0
    - mpmath==1.3.0
    - msgpack==1.0.8
    - mujoco==2.3.7
    - mujoco-py==2.0.2.8
    - multidict==6.0.5
    - mypy-extensions==1.0.0
    - networkx==3.1
    - ninja==1.11.1.1
    - numpy==1.23.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.560.30
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.68
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - onnx==1.17.0
    - openai==1.97.1
    - opencv-python==4.10.0.84
    - packaging==24.1
    - pandas==2.0.3
    - pathtools==0.1.2
    - pillow==10.0.1
    - pip==24.3.1
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.2.2
    - progressbar==2.5
    - promise==2.3
    - protobuf==3.20.3
    - psutil==5.9.6
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pycparser==2.22
    - pydantic==2.8.2
    - pydantic-core==2.20.1
    - pyglet==2.0.10
    - pyopengl==3.1.7
    - pyparsing==3.1.4
    - python-dateutil==2.8.2
    - pytz==2023.4
    - pyvirtualdisplay==3.0
    - pyyaml==6.0.1
    - rapidfuzz==3.9.7
    - ray==1.13.0
    - referencing==0.35.1
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - rl-games==1.6.1
    - rpds-py==0.20.0
    - rsa==4.9
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - sentry-sdk==2.43.0
    - setproctitle==1.3.3
    - setuptools==75.3.0
    - shortuuid==1.0.13
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - sympy==1.13.2
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - torch==1.4.0
    - torchvision==0.19.0
    - tqdm==4.66.5
    - triton==2.0.0
    - typing-extensions==4.12.2
    - typing-inspect==0.9.0
    - tzdata==2023.4
    - urllib3==2.1.0
    - virtualenv==20.26.3
    - wandb==0.22.3
    - wcwidth==0.2.13
    - werkzeug==3.0.4
    - wheel==0.45.1
    - yarl==1.9.8
    - zipp==3.17.0
prefix: /home/lpy/anaconda3/envs/Metaworld-v2

